#!/usr/bin/env python3
"""Emit a VMD scenery script that draws Tutorial 7's analytic exit tunnel.

The cylinder synthesis (`topo-cylinder`) has **no ribosome beads** -- the tunnel
is a pure force. To *show* it in the process GIF we draw it as VMD ``graphics``
on their own molecule: the cylindrical **bore**, the closed **PTC** end cap, and
the semi-transparent **exit-face wall** (an annulus whose hole is the bore). The
geometry is read from the same ``cylinder.ini`` that drove the run, so the drawn
tunnel always matches the forces the chain actually felt.

The output is meant to be passed to ``render_cg.py --extra-tcl <file>``.

    python cylinder_tunnel_tcl.py -f cylinder.ini -o tunnel.tcl

This is a headless-render companion to ``make_movie_cylinder.py`` (which writes
an *interactive* tunnel-aware ``movie.tcl``); both read the same geometry.
"""
from __future__ import annotations

import argparse

from topo.csp.cylinder import read_cylinder_config

NM_TO_A = 10.0


def tunnel_tcl(ini: str, wall_outer_nm: float | None = None) -> str:
    """Build the tunnel-graphics TCL string from a ``cylinder.ini``."""
    p = read_cylinder_config(ini, verbose=False).params
    x_lo = p.tunnel_x_lo_nm * NM_TO_A
    x_exit = (p.tunnel_x_lo_nm + p.tunnel_length_nm) * NM_TO_A
    r = p.tunnel_radius_nm * NM_TO_A
    y0, z0 = (c * NM_TO_A for c in p.tunnel_center_nm)
    rout = ((p.tunnel_radius_nm + 3.0) if wall_outer_nm is None else wall_outer_nm) * NM_TO_A
    cap = max(0.3 * r, 1.0)

    return f"""# Analytic exit tunnel for Tutorial 7 (drawn on its own molecule).
# Auto-generated by cylinder_tunnel_tcl.py from the run's cylinder.ini.
proc draw_annulus {{mol xpos cy cz rin rout n}} {{
    set pi 3.141592653589793
    set da [expr {{2.0 * $pi / $n}}]
    for {{set i 0}} {{$i < $n}} {{incr i}} {{
        set a0 [expr {{$i * $da}}]; set a1 [expr {{($i + 1) * $da}}]
        set yi0 [expr {{$cy + $rin  * cos($a0)}}]; set zi0 [expr {{$cz + $rin  * sin($a0)}}]
        set yi1 [expr {{$cy + $rin  * cos($a1)}}]; set zi1 [expr {{$cz + $rin  * sin($a1)}}]
        set yo0 [expr {{$cy + $rout * cos($a0)}}]; set zo0 [expr {{$cz + $rout * sin($a0)}}]
        set yo1 [expr {{$cy + $rout * cos($a1)}}]; set zo1 [expr {{$cz + $rout * sin($a1)}}]
        graphics $mol triangle "$xpos $yi0 $zi0" "$xpos $yo0 $zo0" "$xpos $yo1 $zo1"
        graphics $mol triangle "$xpos $yi0 $zi0" "$xpos $yo1 $zo1" "$xpos $yi1 $zi1"
    }}
}}

set tun [mol new]
mol rename $tun "tunnel"

# Bore wall: hollow tube (no caps) from PTC to exit, axis along +x.
graphics $tun material Transparent
graphics $tun color blue
graphics $tun cylinder "{x_lo:.3f} {y0:.3f} {z0:.3f}" "{x_exit:.3f} {y0:.3f} {z0:.3f}" \\
    radius {r:.3f} resolution 60 filled no

# Closed PTC end: thin filled disk at x_lo.
graphics $tun color red
graphics $tun cylinder "{x_lo - cap:.3f} {y0:.3f} {z0:.3f}" "{x_lo:.3f} {y0:.3f} {z0:.3f}" \\
    radius {r:.3f} resolution 60 filled yes

# Infinite exit-face wall at x_exit: a flat annulus (hole = bore). Transparent
# (translucent grey) so the ejected chain stays visible as it passes the wall
# plane; the chain leaves through the central hole (= the bore).
graphics $tun material Transparent
graphics $tun color gray
draw_annulus $tun {x_exit:.3f} {y0:.3f} {z0:.3f} {r:.3f} {rout:.3f} 96
"""


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-f", "--ini", default="cylinder.ini", help="the run's cylinder.ini.")
    ap.add_argument("-o", "--out", default="tunnel.tcl", help="output TCL path.")
    ap.add_argument("--wall-outer", type=float, default=None,
                    help="outer radius of the drawn exit wall (nm; default r+3).")
    args = ap.parse_args(argv)
    with open(args.out, "w") as fh:
        fh.write(tunnel_tcl(args.ini, wall_outer_nm=args.wall_outer))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
