#!/usr/bin/env python3
"""Render a TOPO coarse-grained model to a publication-style figure + process GIF.

This is the shared visualization helper used to generate the ``img/hero.png``
(the folded structure) and ``img/process.gif`` (the trajectory) shown in each
tutorial's ``README.md``. It is deliberately headless and reproducible: it drives
**VMD** in text mode with the built-in **TachyonInternal** ray tracer (ambient
occlusion + shadows), then assembles the frames into a GIF with ImageMagick
``convert``. No display, ffmpeg, or PyMOL required.

The CA chain is drawn as a smooth **Tube** coloured N->C (blue -> green -> red)
by writing the normalized residue index into the ``beta`` field and colouring by
``Beta`` with the ``BGR`` colour scale -- a clean rainbow gradient rather than
VMD's discrete ``ResID`` palette.

Usage
-----
    python render_cg.py --psf traj/traj.psf --dcd traj/traj.dcd --out img \
                        --hero last --stride 1

    # a single static structure (no trajectory):
    python render_cg.py --pdb P0CX28_clean.pdb --out img --hero 0 --no-gif

Requires ``vmd`` and ``convert`` on ``PATH``.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile


def _tcl(topology: str, trajectory: str | None, tga_dir: str, *,
         hero_frame: str, gif_stride: int, align: bool,
         rotx: float, roty: float, scale: float,
         tube_radius: float, res: int, make_gif: bool, color: str,
         select: str, selupdate: bool, extra_tcl: str | None,
         fit_main_only: bool, rep: str, fast: bool, bead_radius: float) -> str:
    """Build the VMD script that loads the model and dumps per-frame + hero TGAs."""
    load = f"mol new {topology} type {{{_mol_type(topology)}}} waitfor all\n"
    if trajectory:
        load += f"mol addfile {trajectory} type {{{_mol_type(trajectory)}}} waitfor all\n"

    # Colour mode: 'gradient' -> smooth N->C rainbow (per-residue beta + BGR);
    # 'chain' -> one categorical colour per connected fragment (multicopy).
    if color == "chain":
        color_rep = "mol color Fragment"
        color_scale = ""
        # scaleminmax must run AFTER mol addrep (rep 0 must exist); no-op here.
        scale_fix = "# (per-fragment colour: no beta range to fix)"
    else:
        color_rep = "mol color Beta"
        color_scale = "color scale method BGR"
        # Pin the Beta colour range to [0,1] so the N->C gradient spans the full
        # scale. Essential for all-atom PDBs, whose non-CA atoms keep large
        # B-factors that would otherwise auto-range and wash the tube blue.
        scale_fix = "mol scaleminmax $molid 0 0.0 1.0"

    # A CG PSF/PDB is CA-only, but "name CA" is harmless if names differ (the
    # selection falls back to "all" when it is empty).
    return f"""# Auto-generated by render_cg.py -- headless Tachyon render of a TOPO CG model.
{load}
set molid [molinfo top]

# --- colour by chain position: normalized residue index -> beta ------------
set sel [atomselect $molid "name CA"]
if {{[$sel num] == 0}} {{ $sel delete; set sel [atomselect $molid "all"] }}
set nca [$sel num]
set betas {{}}
for {{set i 0}} {{$i < $nca}} {{incr i}} {{
    lappend betas [expr {{$nca > 1 ? double($i)/($nca-1) : 0.0}}]
}}
$sel set beta $betas
$sel delete

# --- remove rigid-body tumbling so the GIF view is steady ------------------
set nframes [molinfo $molid get numframes]
{_align_block() if align and trajectory else "# (alignment disabled)"}

# --- representation --------------------------------------------------------
{_rep_block(rep, color_rep, select, scale_fix, color_scale, selupdate, tube_radius, res, bead_radius)}

# --- global look -----------------------------------------------------------
# fast=preview: no ambient occlusion / shadows -> Tachyon renders in ~0.1 s/frame
# (vs seconds) so you can check composition before the high-quality pass.
display projection Orthographic
color Display Background white
axes location off
display depthcue off
display shadows {"off" if fast else "on"}
display ambientocclusion {"off" if fast else "on"}
display aoambient 0.85
display aodirect 0.55

# --- view + scenery --------------------------------------------------------
# When fit_main_only is set, fit the camera to the nascent chain FIRST (before
# the big ribosome loads), so scenery is context that may overflow the frame
# rather than shrinking the chain. Otherwise fit to the whole scene (chain +
# small tunnel graphics), which frames tut-7's compact tunnel nicely.
set hero {_hero_expr(hero_frame)}
animate goto $hero
{_view_and_scenery(extra_tcl, fit_main_only, rotx, roty, scale)}
mol top $molid

# --- hero frame ------------------------------------------------------------
render TachyonInternal {tga_dir}/hero.tga
puts "HERO_DONE $hero"

# --- per-frame dump for the GIF -------------------------------------------
{_gif_loop(tga_dir, gif_stride) if (make_gif and trajectory) else "# (gif disabled)"}
puts "ALL_DONE"
quit
"""


def _rep_block(rep: str, color_rep: str, select: str, scale_fix: str,
               color_scale: str, selupdate: bool, tube_radius: float,
               res: int, bead_radius: float) -> str:
    """Emit the mol-representation commands for the chosen style.

    'tube'  -> one smooth spline tube (best for whole folded proteins).
    'beads' -> VDW spheres + Licorice bonds (like ``topo.csp.movie``); it draws
               only *selected* atoms/bonds, so a per-frame ``--select`` cleanly
               hides sentinel-parked beads with no spline streak to them.
               bead_radius sizes the spheres (bump it up for a zoomed-out view
               so the thin threading chain stays visible).
    """
    su = "on" if selupdate else "off"
    if rep == "beads":
        # Two reps (VDW + Licorice); scaleminmax must be pinned on each.
        return f"""mol delrep 0 $molid
mol representation VDW {bead_radius} 16
{color_rep}
mol selection {{{select}}}
mol material AOChalky
mol addrep $molid
{scale_fix}
mol selupdate 0 $molid {su}
mol representation Licorice 0.6 16
{color_rep}
mol selection {{{select}}}
mol material AOChalky
mol addrep $molid
{scale_fix.replace(' 0 ', ' 1 ') if scale_fix.startswith('mol scaleminmax') else scale_fix}
mol selupdate 1 $molid {su}
{color_scale}"""
    return f"""mol delrep 0 $molid
mol representation Tube {tube_radius} {res}
{color_rep}
mol selection {{{select}}}
mol material AOChalky
mol addrep $molid
{scale_fix}
{color_scale}
{"mol selupdate 0 $molid on" if selupdate else "# (static selection)"}"""


def _view_and_scenery(extra_tcl: str | None, fit_main_only: bool,
                      rotx: float, roty: float, scale: float) -> str:
    """Order the view-fit and scenery source so the camera lands where we want.

    fit_main_only=True: fit to the main molecule, THEN load scenery (ribosome
    overflows the frame as context). False: load scenery first, then fit to the
    whole scene (small tunnel graphics are included in the frame).
    """
    fit = f"display resetview\nrotate x by {rotx}\nrotate y by {roty}\nscale by {scale}"
    src = f"source {extra_tcl}" if extra_tcl else "# (no extra scenery)"
    if fit_main_only:
        return f"{fit}\n{src}"
    return f"{src}\n{fit}"


def _mol_type(path: str) -> str:
    ext = os.path.splitext(path)[1].lower().lstrip(".")
    return {"pdb": "pdb", "psf": "psf", "dcd": "dcd"}.get(ext, ext)


def _hero_expr(hero_frame: str) -> str:
    if hero_frame == "last":
        return "[expr {$nframes - 1}]"
    if hero_frame in ("first", "0"):
        return "0"
    return str(int(hero_frame))


def _align_block() -> str:
    return """set ref [atomselect $molid "name CA" frame 0]
if {[$ref num] == 0} { $ref delete; set ref [atomselect $molid "all" frame 0] }
set mov [atomselect $molid "name CA"]
if {[$mov num] == 0} { $mov delete; set mov [atomselect $molid "name CA"] }
set allsel [atomselect $molid "all"]
for {set f 0} {$f < $nframes} {incr f} {
    $mov frame $f
    $allsel frame $f
    $allsel move [measure fit $mov $ref]
}
$ref delete; $mov delete; $allsel delete"""


def _gif_loop(tga_dir: str, stride: int) -> str:
    return f"""set fnum 0
for {{set f 0}} {{$f < $nframes}} {{incr f {stride}}} {{
    animate goto $f
    render TachyonInternal {tga_dir}/frame_[format %04d $fnum].tga
    incr fnum
}}
puts "GIF_FRAMES $fnum"""


def _run(cmd: list[str]) -> None:
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def render(topology: str, out_dir: str, *, trajectory: str | None = None,
           hero_frame: str = "0", gif_stride: int = 1, align: bool = True,
           make_gif: bool = True, width: int = 520, delay: int = 8,
           rotx: float = -30.0, roty: float = 25.0, scale: float = 1.1,
           tube_radius: float = 0.8, res: int = 20, color: str = "gradient",
           select: str = "name CA", selupdate: bool = False,
           extra_tcl: str | None = None, fit_main_only: bool = False,
           rep: str = "tube", fast: bool = False, bead_radius: float = 1.4,
           vmd: str = "vmd", verbose: bool = True) -> None:
    """Render ``hero.png`` (+ ``process.gif``) for a CG model into ``out_dir``."""
    os.makedirs(out_dir, exist_ok=True)
    tga_dir = tempfile.mkdtemp(prefix="render_cg_")
    try:
        script = _tcl(topology, trajectory, tga_dir, hero_frame=hero_frame,
                      gif_stride=gif_stride, align=align, rotx=rotx, roty=roty,
                      scale=scale, tube_radius=tube_radius, res=res,
                      make_gif=make_gif, color=color, select=select,
                      selupdate=selupdate, extra_tcl=extra_tcl,
                      fit_main_only=fit_main_only, rep=rep, fast=fast,
                      bead_radius=bead_radius)
        tcl_path = os.path.join(tga_dir, "render.tcl")
        with open(tcl_path, "w") as fh:
            fh.write(script)

        if verbose:
            print(f"[render_cg] VMD render of {os.path.basename(topology)}"
                  f"{' + ' + os.path.basename(trajectory) if trajectory else ''} ...")
        _run([vmd, "-dispdev", "text", "-e", tcl_path])

        # hero: trim whitespace, pad with a small white margin, size to width.
        hero_png = os.path.join(out_dir, "hero.png")
        _run(["convert", os.path.join(tga_dir, "hero.tga"),
              "-trim", "+repage", "-bordercolor", "white", "-border", "18",
              "-resize", f"{width}x", hero_png])
        if verbose:
            print(f"[render_cg] wrote {hero_png}")

        if make_gif and trajectory:
            frames = sorted(f for f in os.listdir(tga_dir)
                            if f.startswith("frame_") and f.endswith(".tga"))
            if frames:
                gif_png = os.path.join(out_dir, "process.gif")
                frame_paths = [os.path.join(tga_dir, f) for f in frames]
                # Uniform crop to the union content box. Per-image -trim jitters
                # (each frame's box differs); no trim at all leaves wide layouts
                # (e.g. the multicopy strip) marooned in VMD's tall square canvas
                # of whitespace. Compute ONE box that contains the content of
                # every frame -- min across the stack is the darkest pixel, i.e.
                # the union of the dark tube on the white background -- then crop
                # all frames to it and border/resize exactly like the hero, so the
                # GIF is tight *and* steady and the hero/GIF pair sits balanced.
                box = subprocess.run(
                    ["convert", *frame_paths, "-evaluate-sequence", "min",
                     "-format", "%@", "info:"],
                    check=True, capture_output=True, text=True).stdout.strip()
                _run(["convert", "-delay", str(delay), "-loop", "0",
                      *frame_paths, "-coalesce", "-crop", box, "+repage",
                      "-bordercolor", "white", "-border", "18",
                      "-resize", f"{width}x", "-layers", "Optimize", gif_png])
                if verbose:
                    print(f"[render_cg] wrote {gif_png} ({len(frames)} frames)")
    finally:
        shutil.rmtree(tga_dir, ignore_errors=True)


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    src = ap.add_argument_group("input (give --psf+--dcd, or --pdb)")
    src.add_argument("--psf", help="CG topology (PSF).")
    src.add_argument("--dcd", help="trajectory (DCD) to animate.")
    src.add_argument("--pdb", help="a single structure (PDB); use instead of --psf/--dcd.")
    ap.add_argument("--out", required=True, help="output folder (writes hero.png / process.gif).")
    ap.add_argument("--hero", default="0",
                    help="hero frame: 'first'/'0', 'last', or an integer (default 0).")
    ap.add_argument("--stride", type=int, default=1, help="GIF frame stride (default 1).")
    ap.add_argument("--no-align", action="store_true", help="do not RMSD-align frames.")
    ap.add_argument("--no-gif", action="store_true", help="render only the hero PNG.")
    ap.add_argument("--width", type=int, default=520, help="output width in px (default 520).")
    ap.add_argument("--delay", type=int, default=8, help="GIF inter-frame delay (1/100 s).")
    ap.add_argument("--rotx", type=float, default=-30.0)
    ap.add_argument("--roty", type=float, default=25.0)
    ap.add_argument("--scale", type=float, default=1.1)
    ap.add_argument("--radius", type=float, default=0.8, help="tube radius.")
    ap.add_argument("--color", choices=["gradient", "chain"], default="gradient",
                    help="'gradient' = N->C rainbow; 'chain' = per-fragment colour.")
    ap.add_argument("--select", default="name CA",
                    help="VMD selection for the tube (default 'name CA').")
    ap.add_argument("--selupdate", action="store_true",
                    help="re-evaluate --select every frame (e.g. hide sentinel-parked beads).")
    ap.add_argument("--extra-tcl", default=None,
                    help="a TCL file sourced after the reps (draw tunnel/ribosome scenery).")
    ap.add_argument("--fit-main-only", action="store_true",
                    help="fit the camera to the main molecule before scenery loads "
                         "(scenery like a big ribosome becomes overflow context).")
    ap.add_argument("--rep", choices=["tube", "beads"], default="tube",
                    help="'tube' = smooth spline (folded proteins); 'beads' = VDW+Licorice "
                         "(synthesis movies: clean with per-frame --select).")
    ap.add_argument("--fast", action="store_true",
                    help="preview mode: disable ambient occlusion + shadows (~0.1 s/frame) "
                         "to check composition before the high-quality pass.")
    ap.add_argument("--bead-radius", type=float, default=1.4,
                    help="VDW sphere radius for --rep beads (bump up for a zoomed-out view).")
    args = ap.parse_args(argv)

    if args.pdb:
        topology, trajectory = args.pdb, args.dcd
    elif args.psf:
        topology, trajectory = args.psf, args.dcd
    else:
        ap.error("give --pdb, or --psf (optionally with --dcd)")

    render(topology, args.out, trajectory=trajectory, hero_frame=args.hero,
           gif_stride=args.stride, align=not args.no_align,
           make_gif=not args.no_gif, width=args.width, delay=args.delay,
           rotx=args.rotx, roty=args.roty, scale=args.scale,
           tube_radius=args.radius, color=args.color, select=args.select,
           selupdate=args.selupdate, extra_tcl=args.extra_tcl,
           fit_main_only=args.fit_main_only, rep=args.rep, fast=args.fast,
           bead_radius=args.bead_radius)


if __name__ == "__main__":
    main()
