#!/usr/bin/env python3
"""Emit a VMD scenery script that loads a static CG ribosome as context.

Tutorial 8 synthesizes the nascent chain **on TOPO's coarse-grained ribosome**
(`ribosome_trunc.pdb`). To *show* that ribosome in the process GIF we load it as
a separate, static molecule drawn as a translucent silver bead cloud -- the same
idea as the ribosome block in ``topo.csp.movie`` / ``make_movie_cylinder.py``,
but as a standalone snippet for ``render_cg.py --extra-tcl``.

    python ribosome_scenery_tcl.py -p 4c5c/ribosome_trunc.pdb -o ribo.tcl

Pair with ``render_cg.py --fit-main-only`` so the camera stays on the (much
smaller) nascent chain and the ribosome is context around it.
"""
from __future__ import annotations

import argparse


def ribosome_tcl(pdb: str, radius: float = 1.0, colorid: int = 6,
                 material: str = "Ghost") -> str:
    """Build TCL that loads ``pdb`` as a see-through silver ribosome cloud.

    A dense 4575-bead ``Transparent`` cloud reads as an opaque blob that buries
    the nascent chain, so use the near-transparent ``Ghost`` material and a
    modest bead radius: the ribosome becomes a ghostly context the coloured
    chain clearly shows through.

    radius : VDW bead radius (A). colorid : VMD ColorID (6 = silver).
    material : VMD material (Ghost = very transparent).
    """
    return f"""# Static CG ribosome scenery for Tutorial 8 (its own molecule).
# Auto-generated by ribosome_scenery_tcl.py.
set ribo [mol new {pdb} type pdb waitfor all]
mol rename $ribo "ribosome"
mol delrep 0 $ribo
mol representation VDW {radius} 12
mol color ColorID {colorid}
mol selection {{all}}
mol material {material}
mol addrep $ribo
"""


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-p", "--pdb", required=True, help="the CG ribosome PDB.")
    ap.add_argument("-o", "--out", default="ribo.tcl", help="output TCL path.")
    ap.add_argument("--radius", type=float, default=1.0, help="VDW bead radius (A).")
    ap.add_argument("--colorid", type=int, default=6, help="VMD ColorID (6 = silver).")
    ap.add_argument("--material", default="Ghost", help="VMD material (Ghost = very transparent).")
    args = ap.parse_args(argv)
    with open(args.out, "w") as fh:
        fh.write(ribosome_tcl(args.pdb, radius=args.radius, colorid=args.colorid,
                              material=args.material))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
