# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/stable/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
# Add project root so autodoc can find the topo package
sys.path.insert(0, os.path.abspath('..'))


# -- Project information -----------------------------------------------------

project = u'TOPO'
copyright = u'2026, Quyen Vu'
author = u'Quyen Vu'

# Version: auto year.month when building from a tag push (CI); else defaults
import datetime
_github_ref = os.environ.get('GITHUB_REF', '')
if _github_ref.startswith('refs/tags/'):
    version = release = datetime.datetime.utcnow().strftime('%Y.%m')
else:
    version = '2026.1'
    release = 'rc1'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# See: https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html
autodoc_default_options = {
    # 'members': True,
    #'undoc-members': True,
    'private-members': True,
    #'special-members': True,
    #'inherited-members': True,
    #'show-inheritance': True
}

autosummary_generate = True

# Render a class's "Attributes" docstring section as inline ``:ivar:`` fields
# instead of standalone ``.. attribute::`` directives. Without this, napoleon emits
# a separate object description for each documented attribute, which then collides
# with the one autodoc already generates for the same dataclass field -> "duplicate
# object description" warnings (e.g. topo.csp.protocol.CSPConfig/RunParams fields).
napoleon_use_ivar = True

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.githubpages',
    'myst_parser',          # parse Markdown (.md) sources, e.g. the tutorials
]

# Generate anchor slugs for Markdown headings up to level 3 so intra-page links
# like `[step 5](#5-visualize-optional)` in the tutorial READMEs resolve.
myst_heading_anchors = 3
try:
    import rst2pdf
    extensions.insert(0, 'rst2pdf.pdfbuilder')
except ImportError:
    pass  # HTML build works without rst2pdf

pdf_documents = [('index', u'rst2pdf', u'TOPO', u'Quyen Vu'),]


#mathjax_config = {
#    'extensions': ['tex2jax.js'],
#    'jax': ['input/TeX', 'output/HTML-CSS'],
#}

# The sidebar (Furo's own components + a version switcher) is configured via
# html_sidebars near the bottom of this file, in the sphinx-polyversion section.



# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', '.md']
# source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store',
                    # sphinx-apidoc (build_docs.sh) regenerates these two package
                    # pages, but topo.parameters / topo.reporter have curated API
                    # pages under modules/ and are intentionally omitted from the
                    # topo.rst toctree. Exclude the apidoc leftovers so they don't
                    # produce duplicate-object-description / orphan-doc warnings.
                    'topo.parameters.rst', 'topo.reporter.rst']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'furo'

# Theme options are theme-specific. Furo is a modern, responsive theme; the
# options below tune its sidebar/navigation. Full-width content and wrapping
# tables are handled in _static/custom.css (see html_css_files).
html_theme_options = {
    'navigation_with_keys': True,
    'sidebar_hide_name': False,
    # Source-repository links shown in the right-hand sidebar.
    'source_repository': 'https://github.com/vuqv/topo/',
    'source_branch': 'main',
    'source_directory': 'docs/',
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
# Standalone, self-contained interactive diagrams (their own full-page HTML, not
# Sphinx pages). html_extra_path copies the folder's *contents* verbatim into the
# build root, so they are served at <site>/architecture.html and <site>/callflow.html
# (linked from diagrams.rst). Keeping the sources in _diagrams/ keeps them out of
# the Sphinx source scan (leading underscore).
html_extra_path = ['_diagrams']
html_logo = "_static/logo.svg"
# Browser-tab icon: the same square contact-map mark (teal + amber read on any
# tab background). Modern browsers render SVG favicons directly.
html_favicon = "_static/logo.svg"
# Custom CSS: full-width content + wrapping tables (see _static/custom.css).
html_css_files = ['custom.css']
# Custom JS: open external links (DOIs, GitHub, OpenMM, ...) in a new tab.
html_js_files = ['external-links.js']
# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'TOPODoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'TOPO.tex', 'TOPO Documentation',
     'TOPO', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'topo', 'TOPO Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'TOPO', 'TOPO Documentation',
     author, 'TOPO', 'Topology-based coarse-grained model for folded proteins.',
     'Miscellaneous'),
]


# -- Multi-version docs (sphinx-polyversion) ---------------------------------
# When the docs are built via ``sphinx-polyversion`` (see docs/poly.py), the driver
# injects the list of built versions through the POLYVERSION_DATA env var. ``load``
# reads it and populates ``html_context`` with ``current`` (this version) and
# ``revisions`` (all built versions, as GitRef namedtuples), which
# ``_templates/versions.html`` renders as a sidebar version switcher.
#
# A plain ``make html`` build has no such env var -> LoadError is swallowed and the
# switcher is simply omitted, so local single-version builds keep working.
try:
    # importing .git registers GitRef with the JSON decoder used by load()
    from sphinx_polyversion.git import GitRef  # noqa: F401
    from sphinx_polyversion import load
    load(globals())  # -> html_context["current"], html_context["revisions"]
except Exception:
    pass

# Furo supplies its own sidebar (nav + search). We list its components explicitly
# so we can insert the version switcher (versions.html) under the search box while
# keeping the rest of Furo's navigation intact.
# Furo's default sidebar order (see furo/theme/furo/theme.conf) with the version
# switcher (versions.html) pinned at the very bottom, below the light/dark toggle.
# Keep the Furo component list in sync with Furo.
html_sidebars = {
    "**": [
        "sidebar/brand.html",
        "sidebar/search.html",
        "sidebar/scroll-start.html",
        "sidebar/navigation.html",
        "sidebar/ethical-ads.html",
        "sidebar/scroll-end.html",
        "sidebar/variant-selector.html",
        "versions.html",
    ]
}

today_fmt = "%B %d, %Y"
